server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
#    name: spring-blog

#  jpa:
#    show-sql: false
#

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: INFO