server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${DB_URL}
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    name: spring-blog

  jpa:
    show-sql: false




#  liquibase:
#    enabled: false



logging:
  level:
    ROOT: INFO