#server:
#  port: ${PORT:5000}

base-url: /api

#spring:
#  application:
#    name: app







spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    class-driver: org.postgresql.Driver


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml


#    url: jdbc:h2:./db
#    username:
#    password:
#    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect













  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  jpa:
#    hibernate:
#      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /swagger.html

jwt:
#  5 min + 10 sec skew
  issuer: alexander
  expiration-msec: 300000
  secret: secret_key
  clock-skew-sec: 10
