server:
  port: ${PORT:5000}

base-url: /api

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:./db
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create



  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

springdoc:
  swagger-ui:
    path: /swagger.html

jwt:
#  5 min + 10 sec skew
  issuer: alexander
  expiration-msec: 300000
  secret: secret_key
  clock-skew-sec: 10
